### ISSUE TITLE
npm start instead of run file?

### ISSUE THREAD

**Issue by phated** [jlongster/blog#1]
Is there a reason why you are using a file named `run` instead of a start script in package.json?

**Comment by jlongster** [comment]
I don't actually use the `run` file in development, I use `gulp run`. The `run` file is part of my production deployment. I use [runit](http://smarden.org/runit/) for service deployment and I think it's the best out there. The `run` script is what it uses to run this as a service on my server.

I probably should decouple it though, but it is kind of nice to easily check the `run` script locally by just running `./run`.

**Comment by phated** [comment]
Makes sense.
