### ISSUE TITLE
it don't work by gulp run

### ISSUE THREAD

**Issue by elover** [jlongster/blog#5]
my gulp is 4.0.0-alpha.1.
![image](https://cloud.githubusercontent.com/assets/4330913/5791315/fe9201a4-9f07-11e4-8605-9b68f5206bc5.png)

**Comment by clearjs** [comment]
Works for me. Did you alter your gulpfile?

**Comment by jlongster** [comment]
Try `npm ls gulp` and make sure you have gulp 4 installed. If you ran `npm install` not sure why it wouldn't work.

**Comment by brandonwoo** [comment]
I got the same error, clean clone from master, revision 6bda982cf47d816bad25eb120ee084b711d94813. is there a particular version of node I should be using?

**Comment by clearjs** [comment]
node v0.11.6 or higher is required, but gulp version is more likely the cause.

**Comment by clearjs** [comment]
Just an idea: globally and locally installed gulp versions might differ. I only use local version (using the first trick from http://stackoverflow.com/a/27241545/118478)

**Comment by jlongster** [comment]
Yep, I only install locally as well. That would be especially prone to error since I'm using gulp4.

**Comment by brandonwoo** [comment]
Hi, thanks for the tip, i did the above but am still getting the following error

> gulp run
[17:41:53] Using gulpfile ~/react/jlong/gulpfile.js
[17:41:53] Starting 'run'...
[17:41:53] Starting '6to5'...
[17:41:55] Finished '6to5' after 2.11 s
[17:41:55] Starting '<anonymous>'...
Error: Cannot find module 'impl/api'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/source/main.js:3:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by tcurdt** [comment]
No luck here either...

        $ npm install
        npm WARN package.json jlongster.com@ No repository field.
        npm WARN deprecated 6to5@2.13.7: 6to5 is now 'babel': https://babeljs.io/blog/2015/02/15/not-born-to-die
        ...
        $ gulp run
        module.js:338
            throw err;
                  ^
        Error: Cannot find module 'memory-fs'
        ...
        $ npm install memory-fs
        $ gulp run
        [16:05:34] Using gulpfile ~/Downloads/frontend/blog-master/gulpfile.js
        [16:05:34] Starting 'backend-watch'...
        [16:05:34] Backend warming up...
        [16:05:35] Starting 'frontend-watch'...
        [16:05:35] Frontend warming up...
        [16:05:35] Finished 'frontend-watch' after 461 μs
        webpack dev server listening at localhost:3000
        [16:05:35] Finished 'backend-watch' after 132 ms
        [16:05:35] Starting 'run'...
        [16:05:35] Finished 'run' after 907 μs
        Hash: 21b4c78bf86eab81c239
        Version: webpack 1.4.15
        Time: 58ms
        chunk    {0} backend.js, backend.js.map (main) 40 [rendered]
            [0] multi main 40 {0} [built] [2 errors]

        ERROR in multi main
        Module not found: Error: Cannot resolve module 'monkey-hot' in /Users/tcurdt/Downloads/frontend/blog-master
         @ multi main

        ERROR in multi main
        Module not found: Error: Cannot resolve module 'webpack/hot/signal.js' in /Users/tcurdt/Downloads/frontend/blog-master
         @ multi main
        Patched!
        module.js:338
            throw err;
                  ^
        Error: Cannot find module '/Users/tcurdt/Downloads/frontend/blog-master/build/backend'
            at Function.Module._resolveFilename (module.js:336:15)
            at Function.Module._load (module.js:278:25)
            at Function.Module.runMain (module.js:501:10)
            at startup (node.js:129:16)
            at node.js:814:3
        Note: The code generator has deoptimised the styling of "/Users/tcurdt/Downloads/frontend/blog-master/static/js/editor/codemirror-4.8/lib/codemirror.js" as it exceeds the max of "100KB".
        Hash: 54943b49d1c2da25006a
        Version: webpack 1.4.15
        Time: 21050ms
        chunk    {0} frontend.js (main) 1684131 [rendered]
            [0] multi main 52 {0} [built]
               factory:0ms building:1ms = 1ms
             + 516 hidden modules
        chunk    {1} 1.frontend.js 284929 {0} [rendered]
             + 9 hidden modules
        chunk    {2} 2.frontend.js 73094 {0} [rendered]
             + 2 hidden modules

        ERROR in ./static/js/main.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/static/js
         @ ./static/js/main.js 21:10-27

        ERROR in ./src/bootstrap.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/src
         @ ./src/bootstrap.js 15:10-27

        ERROR in ./src/routes.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/src
         @ ./src/routes.js 12:10-27

        ERROR in ./src/lib/util.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/src/lib
         @ ./src/lib/util.js 9:10-27

        ERROR in ./static/js/impl/api.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/static/js/impl
         @ ./static/js/impl/api.js 10:10-27

        ERROR in ./src/components/page.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/src/components
         @ ./src/components/page.js 17:10-27

        ERROR in ./src/components/index.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/src/components
         @ ./src/components/index.js 25:10-27

        ERROR in ./src/components/post.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/src/components
         @ ./src/components/post.js 14:10-27

        ERROR in ./src/components/tag.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/src/components
         @ ./src/components/tag.js 12:10-27

        ERROR in ./src/components/archive.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/src/components
         @ ./src/components/archive.js 12:10-27

        ERROR in ./src/components/drafts.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/src/components
         @ ./src/components/drafts.js 16:10-27

        ERROR in ./src/components/edit.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/src/components
         @ ./src/components/edit.js 30:10-27

        ERROR in ./src/components/not-found.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/src/components
         @ ./src/components/not-found.js 12:10-27

        ERROR in ./src/lib/xhr.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/src/lib
         @ ./src/lib/xhr.js 5:10-27

        ERROR in ./src/components/feedback.js
        Module not found: Error: Cannot resolve 'file' or 'directory' /Users/tcurdt/Downloads/frontend/blog-master/build/csp in /Users/tcurdt/Downloads/frontend/blog-master/src/components
         @ ./src/components/feedback.js 10:10-27
        webpack: bundle is now VALID.

**Comment by tcurdt** [comment]
Also tried with gulp4. If gulp4 is required why https://github.com/jlongster/blog/blob/master/package.json#L22 ?

**Comment by nerdgrass** [comment]
Also running into errors with ```gulp run``` after install. I can go to ```localhost:3000``` and I see a directory of everything (unsure what this is exactly), but I can't get anything resembling a site to come up.

My errors look a lot like @tcurdt's:
```
Alexanders-MacBook-Air:blog-react alex$ gulp run
[16:00:42] Using gulpfile ~/Documents/code/nerdgrass/blog-react/gulpfile.js
[16:00:42] Starting 'backend-watch'...
[16:00:42] Backend warming up...
[16:00:42] Starting 'frontend-watch'...
[16:00:42] Frontend warming up...
[16:00:42] Finished 'frontend-watch' after 351 μs
webpack dev server listening at localhost:3000
[16:00:42] Finished 'backend-watch' after 166 ms
[16:00:42] Starting 'run'...
[16:00:42] Finished 'run' after 1.4 ms
Hash: 21b4c78bf86eab81c239
Version: webpack 1.4.15
Time: 74ms
chunk    {0} backend.js, backend.js.map (main) 40 [rendered]
    [0] multi main 40 {0} [built] [2 errors]

ERROR in multi main
Module not found: Error: Cannot resolve module 'monkey-hot' in /Users/alex/Documents/code/nerdgrass/blog-react
 @ multi main

ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack/hot/signal.js' in /Users/alex/Documents/code/nerdgrass/blog-react
 @ multi main
Patched!

module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/alex/Documents/code/nerdgrass/blog-react/build/backend'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Note: The code generator has deoptimised the styling of "/Users/alex/Documents/code/nerdgrass/blog-react/static/js/editor/codemirror-4.8/lib/codemirror.js" as it exceeds the max of "100KB".
Hash: 0d7e0d8484f572f5f7c4
Version: webpack 1.4.15
Time: 24854ms
chunk    {0} frontend.js (main) 1684458 [rendered]
    [0] multi main 52 {0} [built]
       factory:0ms building:1ms = 1ms
     + 516 hidden modules
chunk    {1} 1.frontend.js 285040 {0} [rendered]
     + 9 hidden modules
chunk    {2} 2.frontend.js 73127 {0} [rendered]
     + 2 hidden modules

ERROR in ./static/js/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/static/js
 @ ./static/js/main.js 21:10-27

ERROR in ./src/routes.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/src
 @ ./src/routes.js 12:10-27

ERROR in ./src/lib/util.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/src/lib
 @ ./src/lib/util.js 9:10-27

ERROR in ./src/bootstrap.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/src
 @ ./src/bootstrap.js 15:10-27

ERROR in ./static/js/impl/api.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/static/js/impl
 @ ./static/js/impl/api.js 10:10-27

ERROR in ./src/components/page.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/src/components
 @ ./src/components/page.js 17:10-27

ERROR in ./src/components/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/src/components
 @ ./src/components/index.js 25:10-27

ERROR in ./src/components/post.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/src/components
 @ ./src/components/post.js 14:10-27

ERROR in ./src/components/tag.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/src/components
 @ ./src/components/tag.js 12:10-27

ERROR in ./src/components/archive.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/src/components
 @ ./src/components/archive.js 12:10-27

ERROR in ./src/components/drafts.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/src/components
 @ ./src/components/drafts.js 16:10-27

ERROR in ./src/components/edit.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/src/components
 @ ./src/components/edit.js 30:10-27

ERROR in ./src/components/not-found.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/src/components
 @ ./src/components/not-found.js 12:10-27

ERROR in ./src/lib/xhr.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/src/lib
 @ ./src/lib/xhr.js 5:10-27

ERROR in ./src/components/feedback.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Documents/code/nerdgrass/blog-react/build/csp in /Users/alex/Documents/code/nerdgrass/blog-react/src/components
 @ ./src/components/feedback.js 10:10-27
webpack: bundle is now VALID.
```

**Comment by jlongster** [comment]
> Also tried with gulp4. If gulp4 is required why https://github.com/jlongster/blog/blob/master/package.json#L22 ?

it's not required anymore, I use gulp 3 because I don't use most of gulp's features anymore (mostly use webpack). Not sure about why this won't run for others, but I don't have time to really support this project. It's just my personal blog, sorry.

**Comment by johnxllis** [comment]
Did anyone figure this out? I get the same long list of errors that nerdgrass and tcurdt get.

**Comment by captainill** [comment]
Getting the same issue. Did you resolve this @nerdgrass  or @johnxllis ?
